apiVersion: v1
kind: Namespace
metadata:
  name: <namespace-name>
---
apiVersion: v1
kind: Service
metadata:
  namespace: <namespace-name>
  name: loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: appname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <namespace-name>
  labels:
    app: <appname>
  name: <deploymentname>
spec:
  selector:
    matchLabels:
      app: <appname>
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: <appname>
    spec:
      containers:
      - image: <imagelink>
        name: <imagename>
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 0.2
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: <hpaname>
  namespace: <namespace-name>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploymentname
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50